# MongoDB e PostgreSQL

In [15]:
from pymongo import MongoClient

# Requires the PyMongo package.
# https://api.mongodb.com/python/current

client = MongoClient('mongodb+srv://<user>:<pw>@host/db')
result = client['ITS_NoSQL']['TWITCH'].aggregate([
    {
        '$group': {
            '_id': '$MOST_STREAMED_GAME', 
            'MediaViews': {
                '$avg': '$AVG_VIEWERS_PER_STREAM'
            }, 
            'TotalTime': {
                '$sum': '$TOTAL_TIME_STREAMED'
            }
        }
    }, {
        '$sort': {
            'MediaViews': -1
        }
    }
])
lista = []
for document in result:
    lista.append(document)

lista

[{'_id': 'NBA 2K22', 'MediaViews': 211701.0, 'TotalTime': 2882},
 {'_id': 'Special Events', 'MediaViews': 113156.0, 'TotalTime': 10493},
 {'_id': 'FIFA 21', 'MediaViews': 73795.33333333333, 'TotalTime': 14002},
 {'_id': 'Chess', 'MediaViews': 71906.0, 'TotalTime': 23115},
 {'_id': 'Destiny 2', 'MediaViews': 62148.857142857145, 'TotalTime': 78721},
 {'_id': 'Rocket League', 'MediaViews': 56851.57142857143, 'TotalTime': 28328},
 {'_id': 'Overwatch', 'MediaViews': 56038.42857142857, 'TotalTime': 158922},
 {'_id': 'F1 2019', 'MediaViews': 42554.0, 'TotalTime': 3960},
 {'_id': 'World of Warcraft', 'MediaViews': 40071.0, 'TotalTime': 214340},
 {'_id': 'League of Legends',
  'MediaViews': 37957.607142857145,
  'TotalTime': 716202},
 {'_id': 'Dungeons & Dragons', 'MediaViews': 37121.0, 'TotalTime': 2942},
 {'_id': 'Yu-Gi-Oh! Duel Links', 'MediaViews': 34434.0, 'TotalTime': 7875},
 {'_id': 'Fortnite', 'MediaViews': 33149.2, 'TotalTime': 220342},
 {'_id': 'Music', 'MediaViews': 32878.6, 'TotalTime': 19357},
 {'_id': 'Tekken 7', 'MediaViews': 30590.333333333332, 'TotalTime': 21392},
 {'_id': 'GeoGuessr', 'MediaViews': 30484.0, 'TotalTime': 6241},
 {'_id': 'Magic: The Gathering', 'MediaViews': 30380.0, 'TotalTime': 20799},
 {'_id': 'Variety', 'MediaViews': 29742.25, 'TotalTime': 6438},
 {'_id': 'PUBG: BATTLEGROUNDS',
  'MediaViews': 29630.583333333332,
  'TotalTime': 102823},
 {'_id': 'Counter-Strike',
  'MediaViews': 29185.483870967742,
  'TotalTime': 203574},
 {'_id': 'Dark Souls', 'MediaViews': 25834.0, 'TotalTime': 18785},
 {'_id': 'Poker', 'MediaViews': 25630.5, 'TotalTime': 9540},
 {'_id': 'Path of Exile', 'MediaViews': 25589.2, 'TotalTime': 112323},
 {'_id': 'Dota 2', 'MediaViews': 24849.457142857143, 'TotalTime': 252036},
 {'_id': 'Minecraft', 'MediaViews': 24710.777777777777, 'TotalTime': 242791},
 {'_id': 'Brawlhalla', 'MediaViews': 23674.0, 'TotalTime': 3818},
 {'_id': 'Heroes of Might and Magic III: The Restoration of Erathia',
  'MediaViews': 20779.0,
  'TotalTime': 14745},
 {'_id': 'Street Fighter V', 'MediaViews': 20296.5, 'TotalTime': 5353},
 {'_id': 'NBA 2K19', 'MediaViews': 20081.0, 'TotalTime': 2232},
 {'_id': "Tom Clancy's Rainbow Six Siege",
  'MediaViews': 19768.625,
  'TotalTime': 44047},
 {'_id': 'FINAL FANTASY XIV ONLINE',
  'MediaViews': 19557.5,
  'TotalTime': 21412},
 {'_id': 'Brawl Stars', 'MediaViews': 19274.333333333332, 'TotalTime': 13421},
 {'_id': 'Valorant', 'MediaViews': 19253.0, 'TotalTime': 5032},
 {'_id': 'Hearthstone', 'MediaViews': 18357.214285714286, 'TotalTime': 160310},
 {'_id': 'World of Tanks', 'MediaViews': 18200.5, 'TotalTime': 50561},
 {'_id': 'ASMR', 'MediaViews': 17286.0, 'TotalTime': 23983},
 {'_id': 'Warframe', 'MediaViews': 16920.5, 'TotalTime': 4646},
 {'_id': 'Call of Duty: Warzone', 'MediaViews': 16285.35, 'TotalTime': 178152},
 {'_id': 'Just Chatting',
  'MediaViews': 15975.579766536965,
  'TotalTime': 1527477},
 {'_id': 'Warcraft III', 'MediaViews': 15279.0, 'TotalTime': 279},
 {'_id': 'Talk Shows & Podcasts', 'MediaViews': 14811.0, 'TotalTime': 20516},
 {'_id': 'FIFA 19', 'MediaViews': 14373.0, 'TotalTime': 17777},
 {'_id': 'Madden NFL 21', 'MediaViews': 14111.0, 'TotalTime': 2009},
 {'_id': 'Team Fortress 2', 'MediaViews': 13884.0, 'TotalTime': 5286},
 {'_id': 'World of Warships', 'MediaViews': 13862.0, 'TotalTime': 4664},
 {'_id': 'Super Smash Bros. Ultimate',
  'MediaViews': 13703.5,
  'TotalTime': 14169},
 {'_id': 'Apex Legends',
  'MediaViews': 13558.666666666666,
  'TotalTime': 154073},
 {'_id': 'Old School RuneScape', 'MediaViews': 13143.0, 'TotalTime': 4570},
 {'_id': 'Super Auto Pets', 'MediaViews': 13005.0, 'TotalTime': 7653},
 {'_id': 'Grand Theft Auto V',
  'MediaViews': 12817.783783783783,
  'TotalTime': 410552},
 {'_id': 'Art', 'MediaViews': 12803.5, 'TotalTime': 16228},
 {'_id': 'Escape from Tarkov',
  'MediaViews': 12007.666666666666,
  'TotalTime': 168563},
 {'_id': 'Games + Demos', 'MediaViews': 11536.0, 'TotalTime': 8119},
 {'_id': 'Super Mario Odyssey', 'MediaViews': 11469.0, 'TotalTime': 8186},
 {'_id': 'Teamfight Tactics', 'MediaViews': 11405.7, 'TotalTime': 71360},
 {'_id': 'VALORANT', 'MediaViews': 11176.933333333332, 'TotalTime': 269027},
 {'_id': 'Rust', 'MediaViews': 9892.5, 'TotalTime': 8301},
 {'_id': 'EA Sports FC 24', 'MediaViews': 9515.5, 'TotalTime': 12780},
 {'_id': 'DARK SOULS III', 'MediaViews': 8904.0, 'TotalTime': 13627},
 {'_id': 'Diablo III', 'MediaViews': 8667.25, 'TotalTime': 43806},
 {'_id': 'DayZ', 'MediaViews': 8511.5, 'TotalTime': 25831},
 {'_id': 'Dead by Daylight',
  'MediaViews': 8019.777777777777,
  'TotalTime': 77445},
 {'_id': 'Sekiro: Shadows Die Twice', 'MediaViews': 7090.0, 'TotalTime': 928},
 {'_id': 'IRL', 'MediaViews': 6400.0, 'TotalTime': 2601},
 {'_id': 'Pokemon FireRed/LeafGreen',
  'MediaViews': 6269.0,
  'TotalTime': 20644},
 {'_id': 'ELDEN RING', 'MediaViews': 6192.5, 'TotalTime': 30108},
 {'_id': 'FIFA 23', 'MediaViews': 5830.111111111111, 'TotalTime': 33112},
 {'_id': 'Star Citizen', 'MediaViews': 5800.0, 'TotalTime': 5429},
 {'_id': 'Among Us', 'MediaViews': 5758.0, 'TotalTime': 23255},
 {'_id': 'Sports', 'MediaViews': 5566.214285714285, 'TotalTime': 59999},
 {'_id': 'Garena Free Fire', 'MediaViews': 4866.5, 'TotalTime': 36001},
 {'_id': 'Resident Evil 3: Nemesis', 'MediaViews': 4783.0, 'TotalTime': 17502},
 {'_id': 'Albion Online', 'MediaViews': 4770.0, 'TotalTime': 18903},
 {'_id': 'Call of Duty: Modern Warfare II',
  'MediaViews': 4716.0,
  'TotalTime': 10448},
 {'_id': 'FIFA 22', 'MediaViews': 4629.666666666667, 'TotalTime': 15356},
 {'_id': 'Software and Game Development',
  'MediaViews': 4460.0,
  'TotalTime': 12373},
 {'_id': 'Super Mario World', 'MediaViews': 4404.0, 'TotalTime': 24527},
 {'_id': 'Genshin Impact', 'MediaViews': 4331.75, 'TotalTime': 22404},
 {'_id': 'Ashes of Creation', 'MediaViews': 4090.0, 'TotalTime': 6262},
 {'_id': 'The Binding of Isaac: Repentance',
  'MediaViews': 3693.5,
  'TotalTime': 13118},
 {'_id': 'Sea of Thieves', 'MediaViews': 3659.0, 'TotalTime': 7866},
 {'_id': 'Halo Infinite', 'MediaViews': 3400.0, 'TotalTime': 2911},
 {'_id': 'The Sims 4', 'MediaViews': 3332.0, 'TotalTime': 6722},
 {'_id': 'Phasmophobia', 'MediaViews': 3286.0, 'TotalTime': 7977},
 {'_id': 'Trackmania', 'MediaViews': 2893.2, 'TotalTime': 19196},
 {'_id': 'Super Mario 64', 'MediaViews': 2733.0, 'TotalTime': 16910},
 {'_id': 'Pokemon Pinball', 'MediaViews': 2585.0, 'TotalTime': 1676},
 {'_id': 'iRacing', 'MediaViews': 2316.0, 'TotalTime': 5210},
 {'_id': 'ROBLOX', 'MediaViews': 2305.0, 'TotalTime': 4117},
 {'_id': 'Fitness & Health', 'MediaViews': 2190.0, 'TotalTime': 193},
 {'_id': 'Animals Aquariums and Zoos',
  'MediaViews': 2020.0,
  'TotalTime': 24502},
 {'_id': 'Knight Online', 'MediaViews': 1982.5, 'TotalTime': 6747},
 {'_id': 'RimWorld', 'MediaViews': 1671.0, 'TotalTime': 9763},
 {'_id': 'Street Fighter 6', 'MediaViews': 1623.0, 'TotalTime': 23193},
 {'_id': 'Sabaku Lover', 'MediaViews': 1500.0, 'TotalTime': 300},
 {'_id': 'RuneScape', 'MediaViews': 766.0, 'TotalTime': 12331},
 {'_id': 'Slots', 'MediaViews': 640.0, 'TotalTime': 19420},
 {'_id': 'Virtual Casino',
  'MediaViews': 51.30434782608695,
  'TotalTime': 37578},
 {'_id': 'Marvel Snap', 'MediaViews': 40.0, 'TotalTime': 3491},
 {'_id': 'Overwatch 2', 'MediaViews': 0.0, 'TotalTime': 2470},
 {'_id': 'MORDHAU', 'MediaViews': 0.0, 'TotalTime': 600},
 {'_id': 'Madden NFL 24', 'MediaViews': 0.0, 'TotalTime': 3030},
 {'_id': 'War Thunder', 'MediaViews': 0.0, 'TotalTime': 2220},
 {'_id': 'Honkai: Star Rail', 'MediaViews': 0.0, 'TotalTime': 1727},
 {'_id': 'Casino', 'MediaViews': 0.0, 'TotalTime': 5530},
 {'_id': 'NBA 2K23', 'MediaViews': 0.0, 'TotalTime': 2554}]

In [16]:
import pandas as pd

myDf = pd.DataFrame.from_records(lista)
myDf = myDf.rename(columns={'_id':'gametitle','MediaViews':'mediaviews','TotalTime':'totaltime'})
myDf

             gametitle     mediaviews  totaltime
0             NBA 2K22  211701.000000       2882
1       Special Events  113156.000000      10493
2              FIFA 21   73795.333333      14002
3                Chess   71906.000000      23115
4            Destiny 2   62148.857143      78721
..                 ...            ...        ...
101      Madden NFL 24       0.000000       3030
102        War Thunder       0.000000       2220
103  Honkai: Star Rail       0.000000       1727
104             Casino       0.000000       5530
105           NBA 2K23       0.000000       2554

[106 rows x 3 columns]

## Importiamo su PostgreSQL

Supponendo di avere un database PostgreSQL a cui abbiamo accesso, altrimenti ce lo facciamo con Docker

In [17]:
from sqlalchemy import create_engine, Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# Definire il modello di base
Base = declarative_base()

# Definire il modello della tabella
class TwitchData(Base):
    __tablename__ = 'twitchdata'
    id = Column(Integer, primary_key=True, autoincrement=True)
    gametitle = Column(String, nullable=False)
    mediaviews = Column(Float, nullable=False)
    totaltime = Column(Integer, nullable=False)

# Crea il motore di connessione a PostgreSQL
engine = create_engine('postgresql+psycopg2://usr:pw@host/db')

# Crea la tabella (se non esiste)
Base.metadata.create_all(engine)

# Crea una sessione
Session = sessionmaker(bind=engine)
session = Session()

C:\Users\andre\AppData\Local\Temp\ipykernel_6880\3199640459.py:6: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [18]:
for index, row in myDf.iterrows():
    new_data = TwitchData(
        gametitle=row['gametitle'],
        mediaviews=row['mediaviews'],
        totaltime=row['totaltime']
    )
    session.add(new_data)

# Effettua il commit per salvare i dati
session.commit()

# Chiude la sessione
session.close()

Ora leggiamo i dati:

In [19]:
query = "SELECT * FROM twitchdata"

# Leggiamo i dati direttamente nel DataFrame Pandas
# engine è lo stesso creato prima con l'ORM
df = pd.read_sql(query, engine)
df

      id          gametitle     mediaviews  totaltime
0      1           NBA 2K22  211701.000000       2882
1      2     Special Events  113156.000000      10493
2      3            FIFA 21   73795.333333      14002
3      4              Chess   71906.000000      23115
4      5          Destiny 2   62148.857143      78721
..   ...                ...            ...        ...
313  314      Madden NFL 24       0.000000       3030
314  315        War Thunder       0.000000       2220
315  316  Honkai: Star Rail       0.000000       1727
316  317             Casino       0.000000       5530
317  318           NBA 2K23       0.000000       2554

[318 rows x 4 columns]

## IRIS Dataset

In [20]:
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'

irisData = pd.read_csv(url)
irisData

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [21]:
class IrisData(Base):
    __tablename__ = 'iris_data'
    id = Column(Integer, primary_key=True, autoincrement=True)
    sepal_length = Column('sepal_length', Float)
    sepal_width = Column('sepal_width', Float)
    petal_length = Column('petal_length', Float)
    petal_width = Column('petal_width', Float)
    variety = Column('variety', String)

# Rinomina le colonne del DataFrame per corrispondere ai nomi nel modello ORM
irisData.rename(columns={
    'sepal.length': 'sepal_length',
    'sepal.width': 'sepal_width',
    'petal.length': 'petal_length',
    'petal.width': 'petal_width'
}, inplace=True)

irisData

     sepal_length  sepal_width  petal_length  petal_width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

Creiamo la tabella sul database:

In [22]:
Base.metadata.create_all(engine)

inseriamo i dati

In [23]:
# Crea una sessione
Session = sessionmaker(bind=engine)
session = Session()

# Rinomina le colonne del DataFrame per corrispondere ai nomi nel modello ORM
irisData.rename(columns={
    'sepal.length': 'sepal_length',
    'sepal.width': 'sepal_width',
    'petal.length': 'petal_length',
    'petal.width': 'petal_width'
}, inplace=True)

# Itera su ogni riga del DataFrame e aggiungere i dati al database
for index, row in irisData.iterrows():
    iris = IrisData(
        sepal_length=row['sepal_length'],
        sepal_width=row['sepal_width'],
        petal_length=row['petal_length'],
        petal_width=row['petal_width'],
        variety=row['variety']
    )
    session.add(iris)

# Effettua il commit per salvare i dati
session.commit()

# Chiude la sessione
session.close()

print("Dati inseriti in PostgreSQL")

Dati inseriti in PostgreSQL